### ISSUE TITLE
Display an Error if Attempting to open the Timeline of a Suspended User

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#128]
At the moment, when attempting to open the timeline of a suspended user, TW Blue returns the following traceback, and does not create a buffer.
Traceback (most recent call last):
  File "C:\twblue\src\keyboard_handler\wx_handler.py", line 70, in <lambda>
    self.parent.Bind(wx.EVT_HOTKEY, lambda evt: self.process_key(evt, key_id), id=key_id)
  File "C:\twblue\src\keyboard_handler\wx_handler.py", line 88, in process_key
    self.handle_key(i)
  File "C:\twblue\src\keyboard_handler\main.py", line 47, in handle_key
    return function()
  File "C:\twblue\src\controller\mainController.py", line 795, in open_timeline
    if usr["protected"] == True:
TypeError: string indices must be integers
We should show an error in this case.

**Comment by manuelcortez** [comment]
This seems to be a regression for #115

**Comment by manuelcortez** [comment]
Nvm it's a different topic. Anyway it should be relatively easy to fix the problem. Probably I will do it tomorrow.
