### ISSUE TITLE
Traceback when Shortening URL's

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#158]
### Steps to reproduce.
1. Try to shorten a URL.
### Expected.
the URL should be shortened.
### Actual.
This traceback occurs.
  File "c:\twblue\src\url_shortener\__main__.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "c:\twblue\src\url_shortener\__main__.py", line 19, in shorten
    return service(**kwargs).shorten(url)
  File "c:\twblue\src\url_shortener\shorteners\url_shortener.py", line 15, in shorten
    return self._shorten(url)
  File "c:\twblue\src\url_shortener\shorteners\acortame.py", line 11, in _shorten
    api = urllib.urlopen ("https://acorta.me/api.php?action=shorturl&format=simple&url=" + urllib.quote(url))
  File "C:\Python27\lib\urllib.py", line 87, in urlopen
    return opener.open(url)
  File "C:\Python27\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 443, in open_https
    h.endheaders(data)
  File "C:\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "C:\Python27\lib\ssl.py", line 363, in wrap_socket
    _context=self)
  File "C:\Python27\lib\ssl.py", line 611, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:661)

**Comment by jmdaweb** [comment]
Which operating system and Python version do you have? I have tested it with good results before commiting.
Regards.


From: Mohamed Al-Hajamy
Sent: Saturday, August 12, 2017 3:42 PM
To: manuelcortez/TWBlue
Cc: Subscribed
Subject: [manuelcortez/TWBlue] Traceback when Shortening URL's (#158)

Steps to reproduce.

  1.  Try to shorten a URL.

Expected.

the URL should be shortened.

Actual.

This traceback occurs.
File "c:\twblue\src\url_shortener_main_.py", line 14, in wrapper
return func(*args, **kwargs)
File "c:\twblue\src\url_shortener_main_.py", line 19, in shorten
return service(**kwargs).shorten(url)
File "c:\twblue\src\url_shortener\shorteners\url_shortener.py", line 15, in shorten
return self._shorten(url)
File "c:\twblue\src\url_shortener\shorteners\acortame.py", line 11, in _shorten
api = urllib.urlopen ("https://acorta.me/api.php?action=shorturl&format=simple&url=" + urllib.quote(url))
File "C:\Python27\lib\urllib.py", line 87, in urlopen
return opener.open(url)
File "C:\Python27\lib\urllib.py", line 213, in open
return getattr(self, name)(url)
File "C:\Python27\lib\urllib.py", line 443, in open_https
h.endheaders(data)
File "C:\Python27\lib\httplib.py", line 1038, in endheaders
self._send_output(message_body)
File "C:\Python27\lib\httplib.py", line 882, in _send_output
self.send(msg)
File "C:\Python27\lib\httplib.py", line 844, in send
self.connect()
File "C:\Python27\lib\httplib.py", line 1263, in connect
server_hostname=server_hostname)
File "C:\Python27\lib\ssl.py", line 363, in wrap_socket
_context=self)
File "C:\Python27\lib\ssl.py", line 611, in init
self.do_handshake()
File "C:\Python27\lib\ssl.py", line 840, in do_handshake
self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:661)

**Comment by Mohamed00** [comment]
Python version 2.7.13, Windows 10 version 1703. The SSL issue is happening everywhere actually, even when playing URL's.

**Comment by jmdaweb** [comment]
It’s very strange, I have the same Windows and Python version, and I’m running TWBlue from source too. I’ll perform more tests on virtual machines. Does it work for you, @manuelcortez?

**Comment by Mohamed00** [comment]
It is also occurring when playing audio, but the traceback is slightly different.   File "c:\twblue\src\controller\buffersController.py", line 638, in audio
    sound.URLPlayer.play(url, self.session.settings["sound"]["volume"])
  File "c:\twblue\src\sound.py", line 139, in play
    self.prepare(url)
  File "c:\twblue\src\sound.py", line 106, in prepare
    self.url = url_shortener.unshorten(url)
  File "c:\twblue\src\url_shortener\__main__.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "c:\twblue\src\url_shortener\__main__.py", line 24, in unshorten
    return service(**kwargs).unshorten(url)
  File "c:\twblue\src\url_shortener\shorteners\acortame.py", line 23, in unshorten
    api = urllib.urlopen ("https://acorta.me/api.php?action=expand&format=simple&shorturl=" + urllib.quote(url))
  File "C:\Python27\lib\urllib.py", line 87, in urlopen
    return opener.open(url)
  File "C:\Python27\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 443, in open_https
    h.endheaders(data)
  File "C:\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "C:\Python27\lib\ssl.py", line 363, in wrap_socket
    _context=self)
  File "C:\Python27\lib\ssl.py", line 611, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] EOF occurred in violation of protocol (_ssl.c:661)

**Comment by manuelcortez** [comment]
That is quite strange, I have played lots of audios today for experimenting, and nothing like that happened here. Also shortening URLS works as expected.

**Comment by codeofdusk** [comment]
I can reproduce the error starting from your change to acortame for URL shortening. Tinyurl worked fine before.


Bill

**Comment by jmdaweb** [comment]
Please, test the latest commit and let us know the results. I think it should be fixed now.

**Comment by Mohamed00** [comment]
It's somewhat fixed, however, audio results in a can't open the file traceback for Dropbox links, even if they work, and shortening URL's results in a different error.
Traceback (most recent call last):
  File "c:\twblue\src\controller\messages.py", line 58, in shorten
    self.message.set_text(self.message.get_text().replace(urls[0], url_shortener.shorten(urls[0])))
  File "c:\twblue\src\url_shortener\__main__.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "c:\twblue\src\url_shortener\__main__.py", line 19, in shorten
    return service(**kwargs).shorten(url)
  File "c:\twblue\src\url_shortener\shorteners\url_shortener.py", line 13, in shorten
    return self._shorten(url)
  File "c:\twblue\src\url_shortener\shorteners\acortame.py", line 12, in _shorten
    api = requests.get ("https://acorta.me/api.php?action=shorturl&format=simple&url=" + urllib.quote(url))
  File "C:\Python27\lib\site-packages\requests-2.18.3-py2.7.egg\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests-2.18.3-py2.7.egg\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests-2.18.3-py2.7.egg\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests-2.18.3-py2.7.egg\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests-2.18.3-py2.7.egg\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='acorta.me', port=443): Max retries exceeded with url: /api.php?a
ction=shorturl&format=simple&url=http%3A//www.google.com (Caused by SSLError(SSLError("bad handshake: Error([('SSL routi
nes', 'ssl3_read_bytes', 'tlsv1 alert internal error')],)",),))

**Comment by jmdaweb** [comment]
Please, let’s work separately on each error. As we haven’t never had an https URL shortener, It’s the first time we find this problem. Searching in Google, It seems that is a problem related to OpenSSL. We can’t fix it easily (Python must be built from source), but you can try installing pyopenssl package. If it fixes the problem, we will include it in future versions.
Regards.

**Comment by codeofdusk** [comment]
Traceback (most recent call last):

  File "C:\Users\codeofdusk\twblue\src\controller\messages.py", line 63, in shorten

    self.message.set_text(self.message.get_text().replace(urls[0], url_shortener.shorten(urls[0])))

  File "C:\Users\codeofdusk\twblue\src\url_shortener\__main__.py", line 15, in wrapper

    return func(*args, **kwargs)

  File "C:\Users\codeofdusk\twblue\src\url_shortener\__main__.py", line 20, in shorten

    return service(**kwargs).shorten(url).decode("utf-8")

  File "C:\Users\codeofdusk\twblue\src\url_shortener\shorteners\url_shortener.py", line 13, in shorten

    return self._shorten(url)

  File "C:\Users\codeofdusk\twblue\src\url_shortener\shorteners\acortame.py", line 12, in _shorten

    api = requests.get ("https://acorta.me/api.php?action=shorturl&format=simple&url=" + urllib.parse.quote(url))

  File "C:\Users\codeofdusk\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.18.1-py3.6.egg\requests\api.py", line 72, in get

    return request('get', url, params=params, **kwargs)

  File "C:\Users\codeofdusk\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.18.1-py3.6.egg\requests\api.py", line 58, in request

    return session.request(method=method, url=url, **kwargs)

  File "C:\Users\codeofdusk\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.18.1-py3.6.egg\requests\sessions.py", line 502, in request

    resp = self.send(prep, **send_kwargs)

  File "C:\Users\codeofdusk\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.18.1-py3.6.egg\requests\sessions.py", line 612, in send

    r = adapter.send(request, **kwargs)

  File "C:\Users\codeofdusk\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.18.1-py3.6.egg\requests\adapters.py", line 514, in send

    raise SSLError(e, request=request)

requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert internal error')],)",)

**Comment by jmdaweb** [comment]
I have noticed that my domain has a wrong IPV6 dns record, so it has been updated generating one IPV6 address for acorta.me machine. Please, test again in some minutes.
Regards.

**Comment by codeofdusk** [comment]
This URL shortener is full of ads. I know you said it’s to help support the project but people will not like this at all…


Bill

**Comment by jmdaweb** [comment]
Don’t worry, It’s safe for all. URLS can be shorted and expanded from TWBlue without ads, they are displayed only if you visit the website. In the other hand, a page will be opened for 15 seconds before redirecting to the destination when opening a short URL. This page should show only frames. It’s not as direct as other shorteners, but it has https, so is more secure.
Regards.

**Comment by codeofdusk** [comment]
Absolutely not. Don’t show ads, ever. Users won’t expect that. Users who don’t understand the Spanish text on the site won’t know what’s going on. If this stays, you will lose users. Guaranteed.

 

Bill

**Comment by Mohamed00** [comment]
I agree with @codeofdusk on this. I honestly think we should stick with Tinyurl. People who receive shortened links from TW Blue users will be confused by this, and it could cause more problems in the long run. I understand the reasoning, but this just isn't the way to go about it.

**Comment by ivnc** [comment]
I agree with the claim made by @codeofdusk at https://twitter.com/codeofdusk/status/896519400567840768. At least the users should have the possibility to choose the shortener to use. The tinyurl support is already implemented and doesn't cost anything to maintain it.
In the other hand, regarding the problems with Spanish… I also agree with the comments. English is an universal language, and expanding at least the redirection page to that language will open many doors.

Regards.

**Comment by codeofdusk** [comment]
There are many other languages besides English and Spanish though. There’s no good way to do this.

 

Bill

**Comment by ivnc** [comment]
Yes, but we have to take on count that both TWBlue main maintaines are spanish and that english is probably the most common language nowadays.

Regards.

**Comment by ivnc** [comment]
o, feliz ía.

**Comment by codeofdusk** [comment]
Como?

 

Bill

**Comment by ivnc** [comment]
sorry, it was for my Twitter, but by a reason I don't know the focus skipped to this window.

Regards.

**Comment by jmdaweb** [comment]
Ok, now there is an english link to skip ads in the redirections page. Is the issue fixed? Did it work when I changed the IPV6 address? Can it be closed?

**Comment by Mohamed00** [comment]
Yes, it seems to work now, and this issue can be closed. Installing pyopenssl fixed it.
