### ISSUE TITLE
Database corrupting apon shutdown

### ISSUE THREAD

**Issue by agasoft** [manuelcortez/TWBlue#198]
I have a permenant problem. When I turn off computer with TW Blue active, apon next start, database is always corrupted and rebuilded. Its happening if I have active Tw blue during shutdown. If I exit Tw blue before shutdown, it will not happen. But why application dont close itself before shutdown, instead going to 
[logs.zip](https://github.com/manuelcortez/TWBlue/files/1558567/logs.zip)
database corruption? Log files present.

**Comment by valiant8086** [comment]
Happens to me a lot too. This is related to #191. If we can fix this it sure would be lovely, that is the main difficulty I have with TWBlue. Note that I have the database size set to 0 so it'll be infinite. What often happens is that I have several thousand tweets, and I may be a thousand or so back. So not only do I lose my place, I can't actually get it to fetch enough old ones with my alt+win+page up keystroke to be not missing things in between where I was and what is now the oldest item.

**Comment by codeofdusk** [comment]
I'm the one who developed the database system, and am just seeing these issues. Basically, the program writes back the DB at close, hence why you're getting the corruption. What do you think about the program periodically writing back the DB instead of once at shutdown? How about an option in the menus to write it back manually? Some other solution?

**Comment by trodick** [comment]
> I'm the one who developed the database system, and am just seeing these issues. Basically, the program writes back the DB at close, hence why you're getting the corruption. What do you think about the program periodically writing back the DB instead of once at shutdown? How about an option in the menus to write it back manually? Some other solution?

@codeofdusk Perhaps thread off periodic database flushes, such that the application doesn't become unresponsive. Additionally, I occasionally have the below error, and I can't reproduce it; is it related?

20/11/2019 18:41:44 sessionmanager.session ERROR: Exception while shelvingC:\Users\twkav\AppData\Roaming\TW blue\config\517.18/cache.db
Traceback (most recent call last):
  File "sessions\base.pyo", line 91, in shelve
  File "shelve.pyo", line 133, in __setitem__
  File "bsddb\__init__.pyo", line 279, in __setitem__
  File "bsddb\dbutils.pyo", line 68, in DeadlockWrap
  File "bsddb\__init__.pyo", line 278, in wrapF
DBRunRecoveryError: (-30974, 'DB_RUNRECOVERY: Fatal error, run database recovery -- PANIC: Invalid argument')

Thanks!
