### ISSUE TITLE
Unable to run from source

### ISSUE THREAD

**Issue by Menelion** [manuelcortez/TWBlue#243]
Hi Manuel and team,

I try to run the latest commit from source. I did that before (long ago, actually), and everything went well. Now however I get the following:

```shell
Traceback (most recent call last):
  File "src/main.py", line 22, in <module>
    import sound
  File "D:\repos\git\TwBlue\src\sound.py", line 14, in <module>
    import vlc
  File "C:\Python27\lib\site-packages\vlc.py", line 203, in <module>
    dll, plugin_path  = find_lib()
  File "C:\Python27\lib\site-packages\vlc.py", line 173, in find_lib
    dll = ctypes.CDLL(libname)
  File "C:\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
```

What am I missing? If the DLLs should be moved somewhere, please tell me about that, I'll send a PR with an updated Readme. Thanks!

**Comment by Mohamed00** [comment]
For x86, in the x86 section of Windows dependencies, move the plugins folder, libvlc.dll and libvlccore.dll to the SRC directory. It will also work if you have VLC installed.

**Comment by Menelion** [comment]
Thanks Mohamed, worked like a charm!
