### ISSUE TITLE
with latest commit, impossible to view a tweet conversation

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#249]
### Steps to reproduce.
1. Try to view a conversation.
### Expected.
A buffer should appear with the tweet conversation.
### Actual.
The following traceback is displayed.
Traceback (most recent call last):
  File "c:\twblue\src\keyboard_handler\wx_handler.py", line 70, in <lambda>
    self.parent.Bind(wx.EVT_HOTKEY, lambda evt: self.process_key(evt, key_id), id=key_id)
  File "c:\twblue\src\keyboard_handler\wx_handler.py", line 88, in process_key
    self.handle_key(i)
  File "c:\twblue\src\keyboard_handler\main.py", line 47, in handle_key
    return function()
  File "c:\twblue\src\controller\mainController.py", line 915, in open_conversation
    search.start_stream(start=True)
  File "c:\twblue\src\controller\buffersController.py", line 1419, in start_stream
    val2 = self.session.search(self.name, tweet_mode="extended", *self.args, **self.kwargs)

  File "c:\twblue\src\sessions\twitter\session.py", line 204, in search
    tl = self.twitter.twitter.search(*args, **kwargs)
TypeError: search() takes exactly 1 argument (5 given)

**Comment by manuelcortez** [comment]
Can you try the latest commit?

**Comment by Mohamed00** [comment]
It's working now. Closing.
