### ISSUE TITLE
Impossible to start TWBlue from source in the latest commit

### ISSUE THREAD

**Issue by lukaszgo1** [manuelcortez/TWBlue#280]
When running from sources with Python 2.7 x64 after installing al requirements specified in the requirements.txt I've got this
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    import sound
  File "D:\TWBlue\src\sound.py", line 12, in <module>
    import sound_lib
  File "D:\TWBlue\src\sound_lib\__init__.py", line 1, in <module>
  File "D:\TWBlue\src\sound_lib\output.py", line 7, in <module>

  File "D:\TWBlue\src\sound_lib\external\__init__.py", line 5, in <module>
  File "D:\TWBlue\src\sound_lib\external\pybass_aac.py", line 16, in <module>
  File "D:\TWBlue\src\sound_lib\external\pybass.py", line 61, in <module>
  File "D:\TWBlue\src\sound_lib\external\paths.py", line 8, in <module>
    from functools import wraps
  File "D:\TWBlue\src\platform_utils\paths.py", line 74, in module_path
    @merge_paths
  File "D:\TWBlue\src\platform_utils\paths.py", line 58, in get_module
    import winpaths
AttributeError: 'NoneType' object has no attribute '__file__'

**Comment by manuelcortez** [comment]
Apparently you still need to remove sound_lib, , platform_utils and probably libloader and accessible_output2 from your src directory as the code is making references to those modules present in your folder, not the modules installed by pip.

**Comment by lukaszgo1** [comment]
Removing all of those directories resulted in the following written in the stderr.log
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    import output
  File "D:\TWBlue\src\output.py", line 5, in <module>
    from accessible_output2 import outputs
ImportError: No module named accessible_output2

**Comment by Mohamed00** [comment]
I think @manuelcortez hasn't added accessible_output2 to 
requirements.txt yet. Here's a temporary solution, a copy of the 
library. Place this in your src directory. Note that I'll delete this 
when the issue is resolved. 
https://www.dropbox.com/s/feacquax6tim03n/accessible_output2.7z?dl=1
