### ISSUE TITLE
Various errors with extra functions in python3 self-built executable

### ISSUE THREAD

**Issue by ultrasound1372** [manuelcortez/TWBlue#324]
I have cloned the next-gen branch and I build my own snapshots. I have all of the dependencies necessary. I was able to use pyinstaller to build the executable and run it, after forcing it in two different places in main.spec not to use UPX, passing --noupx, and possibly copying vcruntime140.dll from somewhere else anyway. Now that it is running I've noticed a few things that are beyond simply receiving and sending tweets are broken with strange errors. The following log snippets are taken from a dummy session where I launched it and tried immediately to perform these actions then exited.
Upon attempting to play back a sound from a tweet containing a sndup link.
```
Traceback (most recent call last):
  File "keyboard_handler\wx_handler.py", line 72, in <lambda>
  File "keyboard_handler\wx_handler.py", line 99, in process_key
  File "keyboard_handler\main.py", line 47, in handle_key
  File "controller\mainController.py", line 1229, in audio
  File "controller\buffers\twitterBuffers.py", line 556, in audio
  File "sound.py", line 149, in play
  File "sound.py", line 122, in prepare
AttributeError: module 'url_shortener' has no attribute 'unshorten'
```

Upon typing in a partial username and attempting to use the autocomplete button, specifically within the direct message dialog.
```
Traceback (most recent call last):
  File "controller\messages.py", line 199, in autocomplete_users
  File "extra\autocompletionUsers\completion.py", line 13, in __init__
  File "extra\autocompletionUsers\storage.py", line 8, in __init__
TypeError: config_path() takes 0 positional arguments but 1 was given
Exception ignored in: <function storage.__del__ at 0x00000288F844BD38>
Traceback (most recent call last):
  File "extra\autocompletionUsers\storage.py", line 53, in __del__
AttributeError: 'storage' object has no attribute 'cursor'
```

Upon typing "This is a test!" Into the direct message text box and pressing the spell check button, this happens anywhere else as well.
```
Traceback (most recent call last):
  File "controller\messages.py", line 116, in spellcheck
  File "extra\SpellChecker\spellchecker.py", line 26, in __init__
  File "site-packages\enchant\__init__.py", line 479, in get_param
  File "site-packages\enchant\utils.py", line 170, in decode
AttributeError: 'NoneType' object has no attribute 'decode'
```
I'll try your snapshot and get back to you on that.
Edit: Tried the snapshot built on Oct 4 2019 that's available in your link from #309 and the same errors occur. The log is much more verbose but the same messages are present, except the last one to do with spell checking spits out this one instead.
```
Traceback (most recent call last):
  File "site-packages\enchant\checker\__init__.py", line 144, in __init__
  File "site-packages\enchant\tokenize\__init__.py", line 200, in get_tokenizer
enchant.errors.TokenizerNotFoundError: No tokenizer found for language 'en'
```
So maybe that's more helpful to you.

**Comment by manuelcortez** [comment]
Hello, we're moving everything to build with cx_freeze instead, as pyinstaller executables were flagged by lots of antivirus softwares. That's why you are having such issues as the codebase has been slightly modified for the other setup. Take a look to the appveyor file in the base path of the repo, so you'll see the steps we follow for building executables of the projects.
