### ISSUE TITLE
TWBlue unable to speak when navigating invisible interface

### ISSUE THREAD

**Issue by JessicaTegner** [manuelcortez/TWBlue#339]
Hi.
When using the global shortcuts / invisible interface, twblue doesn't say anything, abut all sounds (for tweets with pcitures / audio and so on) plays as usual.
Here's the trackback from errors.log

Traceback (most recent call last):
  File "output.py", line 25, in setup
  File "accessible_output2\outputs\auto.py", line 12, in __init__
  File "accessible_output2\outputs\jaws.py", line 16, in __init__
  File "libloader\com.py", line 15, in load_com
  File "win32com\client\gencache.py", line 527, in EnsureDispatch
  File "win32com\client\__init__.py", line 96, in Dispatch
  File "win32com\client\__init__.py", line 37, in __WrapDispatch
  File "win32com\client\gencache.py", line 183, in GetClassForCLSID
  File "win32com\client\gencache.py", line 230, in GetModuleForCLSID
AttributeError: module 'win32com.gen_py.105C4321-CB93-11D4-9839-00C0F0214711x0x1x0' has no attribute 'CLSIDToPackageMap'

**Comment by Mohamed00** [comment]
Go into the run dialog and type %tmp%, and delete the gen_py folder in 
the directory that comes up.

**Comment by JessicaTegner** [comment]
yeah. I know that fixes the issue, but less tech savy users wouldn't necessarily know that, that would fix the issue. That is why, I wanted to see if @manuelcortez or someone else, could implement something into TWBlue that could mitigate it.

**Comment by manuelcortez** [comment]
It should be fixed after #369
