### ISSUE TITLE
Direct messages buffer doesn't work.

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#349]
Hi, I noticed that with theTweepy version of TWBlue, the direct messages buffer isn't working and TWBlue doesn't fully launch as a result. The following traceback appears on startup.
21/01/2021 16:02:28 mysc.thread_utils ERROR: Thread 12256 with function <bound method Controller.start of <controller.mainController.Controller object at 0x0000022054913848>>, args of (), and kwargs of {} failed to run.
Traceback (most recent call last):
  File "C:\twblue\src\mysc\thread_utils.py", line 16, in new_func
    func(*a, **k)
  File "C:\twblue\src\controller\mainController.py", line 267, in start
    self.start_buffers(sessions.sessions[i])
  File "C:\twblue\src\controller\mainController.py", line 1326, in start_buffers
    i.start_stream()
  File "C:\twblue\src\controller\buffers\twitterBuffers.py", line 186, in start_stream
    number_of_items = self.session.order_buffer(self.name, val)
  File "C:\twblue\src\sessions\twitter\session.py", line 33, in order_buffer
    return self.order_direct_messages(data)
  File "C:\twblue\src\sessions\twitter\session.py", line 97, in order_direct_messages
    pub.sendMessage("sent-dms-updated", total=sent, account=self.db["user_name"])
  File "C:\Python37\lib\site-packages\pubsub\core\publisher.py", line 216, in sendMessage
    topicObj.publish(**msgData)
  File "C:\Python37\lib\site-packages\pubsub\core\topicobj.py", line 452, in publish
    self.__sendMessage(msgData, topicObj, msgDataSubset)
  File "C:\Python37\lib\site-packages\pubsub\core\topicobj.py", line 482, in __sendMessage
    listener(data, self, allData)
  File "C:\Python37\lib\site-packages\pubsub\core\listener.py", line 237, in __call__
    cb(**kwargs)
  File "C:\twblue\src\controller\mainController.py", line 1609, in update_sent_dms
    sent_dms.put_items_on_list(total)
  File "C:\twblue\src\controller\buffers\twitterBuffers.py", line 294, in put_items_on_list
    tweet = self.compose_function(i, self.session.db, self.session.settings["general"]["relative_times"], self.session.settings["general"]["show_screen_names"], self.session)
  File "C:\twblue\src\sessions\twitter\compose.py", line 85, in compose_direct_message
    original_date = arrow.get(int(item.created_timestamp))
  File "C:\Python37\lib\site-packages\arrow\api.py", line 21, in get
    return _factory.get(*args, **kwargs)
  File "C:\Python37\lib\site-packages\arrow\factory.py", line 176, in get
    return self.type.fromtimestamp(arg, tzinfo=tz)
  File "C:\Python37\lib\site-packages\arrow\arrow.py", line 161, in fromtimestamp
    dt = datetime.fromtimestamp(float(timestamp), tzinfo)
OSError: [Errno 22] Invalid argument.
Manually updating the buffer doesn't appear to work either.

**Comment by manuelcortez** [comment]
Hi,
Have you upgraded all packages, including arrow?

**Comment by Mohamed00** [comment]
Upgrading Arrow fixed the issue, thanks.
