### ISSUE TITLE
Error on translator module

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#355]
When attempting to translate something in TWBlue, the following traceback is raised:
Traceback (most recent call last):
  File "controller\messages.py", line 45, in translate
  File "extra\translator\wx_ui.py", line 49, in __init__
  File "extra\translator\translator.py", line 111, in available_languages
  File "yandex_translate\__init__.py", line 91, in langs
  File "yandex_translate\__init__.py", line 79, in directions
yandex_translate.YandexTranslateException: None

**Comment by manuelcortez** [comment]
Here is the reason behind this issue. Once I logged in the [Yandex Developers portal](https://translate.yandex.com/developers/keys) I have seen the following notification:

> We no longer issue free keys for the Yandex.Translate API. For all existing free keys, there will be a limit of 50,000 symbols as of July 31st and these keys will stop working on August 15th.

So there's that. perhaps we'd use googletrans, despite it might stop working in the near future when google changes their ways to render their sites?
