### ISSUE TITLE
error when installing the latest snapshot

### ISSUE THREAD

**Issue by amirramezani79** [manuelcortez/TWBlue#402]
Hello.
I want to install the latest snapshot in my windows 7 64 bit, but i face this error when opening the program:
Traceback (most recent call last):
  File "__startup__.py", line 104, in run
  File "Console.py", line 15, in run
  File "main.py", line 3, in <module>
  File "win32com\__init__.py", line 5, in <module>
ImportError: DLL load failed while importing win32api: The specified 
module could not be found.
I don't have this problem when installing the latest stable version.

**Comment by manuelcortez** [comment]
It should be fixed already in current version 2021.10.30.
