### ISSUE TITLE
Errors no longer being spoken with latest Tweepy changes

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#403]
STR.
Do something that causes an error, for example sending an empty tweet.
Expected.
The error should be spoken, as it was previously.
Actual.
The error is no longer spoken.
Log fragment.
04/10/2021 20:47:47 root ERROR: Uncaught exception
Traceback (most recent call last):
  File "C:\twblue\src\sessions\twitter\session.py", line 200, in api_call
    val = getattr(self.twitter, call_name)(*args, **kwargs)
  File "C:\Python37\lib\site-packages\tweepy\api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "C:\Python37\lib\site-packages\tweepy\api.py", line 1128, in update_status
    ), status=status, **kwargs
  File "C:\Python37\lib\site-packages\tweepy\api.py", line 259, in request
    raise Forbidden(resp)
tweepy.errors.Forbidden: 403 Forbidden
170 - Missing required parameter: status.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\twblue\src\keyboard_handler\wx_handler.py", line 72, in <lambda>
    self.parent.Bind(wx.EVT_HOTKEY, lambda evt: self.process_key(evt, key_id), id=key_id)
  File "C:\twblue\src\keyboard_handler\wx_handler.py", line 99, in process_key
    self.handle_key(i)
  File "C:\twblue\src\keyboard_handler\main.py", line 47, in handle_key
    return function()
  File "C:\twblue\src\controller\mainController.py", line 760, in post_tweet
    buffer.post_status()
  File "C:\twblue\src\controller\buffers\twitter\base.py", line 102, in post_status
    item = self.session.api_call(call_name="update_status", status=text, _sound="tweet_send.ogg", tweet_mode="extended")
  File "C:\twblue\src\sessions\twitter\session.py", line 203, in api_call
    output.speak(e.reason)
AttributeError: 'Forbidden' object has no attribute 'reason'

**Comment by manuelcortez** [comment]
This should be much better right now. Although it would be nice if you could test some actions where you might find errors. TWBlue should be able to report those normally and raise exceptions when needed.

**Comment by Mohamed00** [comment]
Works now, thanks for the fix.
