### ISSUE TITLE
Translation workflow

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#425]
I think we should improve our translation workflow so we will offer everyone the same opportunity to participate in the translation team for a language. Right now, we are basically restricting access to collaboration to those users who are either in our dropbox translators folder or those with access to git and github, and send pull requests against this repository. Even so, there were certain conflicts caused by people pushing updates to translations that were already worked on in our dropbox folder. I think there should be an easier and better way to manage translations in a way that would allow everyone to participate.

Personally, I have been working for other projects with a Weblate instance. I think we might setup TWBlue to integrate with Weblate, so people would work on weblate and it will push all accepted changes to this repository. This would make easier for people to work on translations without needing to setup dropbox or even use poedit. @jmdaweb, as you were coordinating the translation team, I am especially interested in your opinion regarding this matter.

**Comment by nidza07** [comment]
Hello,
as someone who is working on Serbian translation since recently, I wanted to comment on this issue.
First of all, I wanted to apologize if there was any duplicate work submitted from my side. I never knew a Dropbox folder for translations even existed. Some users notified me that TWBlue's Serbian translation is outdated, and so I submitted pull requests to update it and add the missing documentation, and continued working on it ever since. Thanks for merging them, and of course, if the original translator is still willing to work on it, he can always take over, since the already existing translations were very good, as I said it was mainly outdated.
In addition, if the  workflow won't be changed, it might be a good idea to mention in the Readme that if someone wants to work on a translation, they can request an invitation to the folder.

Now regarding the workflow, I agree that improving it would be nice. I personally don't mind sending pull requests, but of course not everyone knows how to work with Git. Moreover, as it currently stands, it is difficult to generate a translation template (the POT file). Not only do you need Python installed, but you also need to modify the default script.
The default script expects Python 2.7, but the sintax has now been updated for Python  3 and so you need to modify the genpot.bat file to point to a Python 3 installation.
Even when I do this, I am at present unable to  generate the template for documentation / changelog.
I get the following traceback:
Traceback (most recent call last):
  File "pygettext.py", line 627, in <module>
    main()
  File "pygettext.py", line 580, in main
    expanded.extend(getFilesForName(arg))
  File "pygettext.py", line 281, in getFilesForName
    spec = importlib.util.find_spec(name)
  File "C:\Program Files (x86)\Python38-32\lib\importlib\util.py", line 90, in find_spec
    fullname = resolve_name(name, package) if name.startswith('.') else name
  File "C:\Program Files (x86)\Python38-32\lib\importlib\util.py", line 32, in resolve_name
    raise ValueError(f'no package specified for {repr(name)} '
ValueError: no package specified for '../doc/strings.py' (required for relative module names)
Traceback (most recent call last):
  File "pygettext.py", line 627, in <module>
    main()
  File "pygettext.py", line 580, in main
    expanded.extend(getFilesForName(arg))
  File "pygettext.py", line 281, in getFilesForName
    spec = importlib.util.find_spec(name)
  File "C:\Program Files (x86)\Python38-32\lib\importlib\util.py", line 90, in find_spec
    fullname = resolve_name(name, package) if name.startswith('.') else name
  File "C:\Program Files (x86)\Python38-32\lib\importlib\util.py", line 32, in resolve_name
    raise ValueError(f'no package specified for {repr(name)} '
ValueError: no package specified for '../doc/changelog.py' (required for relative module names)

I could be missing a module and / or a different Python version though.

As a last thing and a conclusion, it would be useful if we can be notified before a new release is about to be made so translations can be updated on time.
I prefer not to spam the repository with multiple pull requests as new features are being added and strings changed and would rather submit one PR once the release is nearly completed.
Of course, I understand this isn't always possible, if an urgent update needs to be released, for example.

In any case, I  look forward to what you come up with and continuing to deliver quality translations to all users.
Thanks for your work.

**Comment by manuelcortez** [comment]
Hi there @nidza07, thank you very much for your hard work and for pushing every translation update to the repo. It's really a cool thing and I appreciate that kind of things very much. As you mentionned, currently it is not quite easy to generate translation catalogs. Currently I am in the works to change to Babel, which would make significantly easier to init translations for new catalogs, as well as compiling current translations and updating catalogs when there are new files. In fact, using Babel would be even easier so we can put some code to update catalogs when we push new strings to the repository, and those catalogs might be automatically added to a weblate instance. Weblate is basically a website (that we can host ourselves) where you can define a project, which is basically a translation file. We can, for example, define 3 different projects within TWBlue: Interface, documentation and changelog. Weblate then takes paths to the catalogs (that's why we'd need to constantly update them by ourselves, for example on every commit) and generates a web interface which allows you to translate by filling a form with your translations. That removes the need to use poedit or other kind of software and we would deal with catalogs, all you would need to do is to have an account on such instance, and translate from there. Every time someone translates something new, weblate also generates the needed PO file and pushes a commit to our repository directy updating your translations, so we'd remove completely the situation where you would not have an idea about when we will merge something you translated, because that happens as soon as you save something.

Specifically about TWBlue, I have been thinking in asking everyone willing to help with translations to register into a weblate instance (which I still don't installed yet in the new server I am using), add the projects for TWBlue there and update the repository so it will update catalogs on every commit. That would make our workflow completely automated. Translators wouldn't need to wait for us to generate anything, of course they wouldn't have to generate anything themselves, and it will reduce workload of @jmdaweb as he wouldn't need to go to a dropbox folder and copy changes in order to update catalogs in the repository.
