### ISSUE TITLE
Cannot start from sources

### ISSUE THREAD

**Issue by lukaszgo1** [manuelcortez/TWBlue#438]
TWBlue fails to start from sources on my machine. After I've installed all dependencies and executed `py src\main.py` the following is shown on the console:
```
[00722448] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[050948c0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
```
The end of the debug.log is as follows:
```
13/11/2021 12:38:07 core.output DEBUG: Initializing output subsystem.
13/11/2021 12:38:07 root ERROR: Uncaught exception
Traceback (most recent call last):
  File "src\main.py", line 145, in <module>
    setup()
  File "src\main.py", line 77, in setup
    from controller import settings
  File "D:\my_repos\TWBlue\src\controller\settings.py", line 11, in <module>
    from wxUI.dialogs import configuration
  File "D:\my_repos\TWBlue\src\wxUI\dialogs\__init__.py", line 1, in <module>
    from . import baseDialog, trends, configuration, lists, search, find, show_user, update_profile, urlList, userSelection, utils, filterDialogs, userAliasDialogs
  File "D:\my_repos\TWBlue\src\wxUI\dialogs\search.py", line 5, in <module>
    from extra import translator
  File "D:\my_repos\TWBlue\src\extra\translator\__init__.py", line 4, in <module>
    from . import translator
  File "D:\my_repos\TWBlue\src\extra\translator\translator.py", line 3, in <module>
    from googletrans import Translator, LANGUAGES
  File "D:\my_repos\TWBlue\env\lib\site-packages\googletrans\__init__.py", line 6, in <module>
    from googletrans.client import Translator
  File "D:\my_repos\TWBlue\env\lib\site-packages\googletrans\client.py", line 13, in <module>
    import httpx
  File "D:\my_repos\TWBlue\env\lib\site-packages\httpx\__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "D:\my_repos\TWBlue\env\lib\site-packages\httpx\_api.py", line 4, in <module>
    from ._client import Client
  File "D:\my_repos\TWBlue\env\lib\site-packages\httpx\_client.py", line 30, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "D:\my_repos\TWBlue\env\lib\site-packages\httpx\_transports\default.py", line 92, in <module>
    httpcore.CloseError: CloseError,
AttributeError: module 'httpcore' has no attribute 'CloseError'

```
On the same machine binary version of TWBlue works correctly.

**Comment by lukaszgo1** [comment]
This problem is due to new version of httpcore which has just been released and httpx is not yet compatible with it (PR which introduces compatibility is https://github.com/encode/httpx/pull/1935). Since TWBlue works correctly when older versions are installed and this would be solved in a few days I'm closing this issue.
