### ISSUE TITLE
TWBlue Doesn't Work with Twitter

### ISSUE THREAD

**Issue by SeanTolstoyevski** [manuelcortez/TWBlue#533]
Greetings all,

When I wanted to use TWBlue today, I saw that none of my accounts' sessions could be created. I am sharing the logs below.
This situation persists even when I try to delete my `config` directory and create a new authorization from scratch.

Additionally, I would like to say that TWBlue is no longer available for "allowed" apps from the settings on Twitter. There is only the "Quinter" application that I have connected to my account a long time ago.
It seems that with the new Twitter, TWBlue's API access permissions have been removed :) .

***

I don't know the details but I think it may be because Twitter is now charging for the API. If there are any policy changes on this topic, I think we need to support TWBlue as a community so that it can work in harmony with Twitter, and as a frequent user of this great program, I can support myself.
Can you share the developments on this issue?
What can we do, what should we do?

@manuelcortez 

`error.log` output:

```txt
08/04/2023 15:19:14 root ERROR: Uncaught exception
Traceback (most recent call last):
  File "tweepy\auth.py", line 62, in _get_request_token
  File "requests_oauthlib\oauth1_session.py", line 287, in fetch_request_token
  File "requests_oauthlib\oauth1_session.py", line 369, in _fetch_token
requests_oauthlib.oauth1_session.TokenRequestDenied: Token request failed with code 401, response was '{"errors":[{"code":32,"message":"Could not authenticate you."}]}'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tweepy\auth.py", line 76, in get_authorization_url
  File "tweepy\auth.py", line 64, in _get_request_token
tweepy.errors.TweepyException: Token request failed with code 401, response was '{"errors":[{"code":32,"message":"Could not authenticate you."}]}'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sessionmanager\wxUI.py", line 75, in on_new_twitter_account
  File "pubsub\core\publisher.py", line 216, in sendMessage
  File "pubsub\core\topicobj.py", line 452, in publish
  File "pubsub\core\topicobj.py", line 482, in __sendMessage
  File "pubsub\core\listener.py", line 237, in __call__
  File "sessionmanager\sessionManager.py", line 132, in manage_new_account
  File "sessions\twitter\session.py", line 160, in authorise
  File "tweepy\auth.py", line 81, in get_authorization_url
tweepy.errors.TweepyException: Token request failed with code 401, response was '{"errors":[{"code":32,"message":"Could not authenticate you."}]}'.
08/04/2023 15:20:58 mysc.thread_utils ERROR: Thread 17328 with function <bound method Controller.start of <controller.mainController.Controller object at 0x000001FC38204700>>, args of (), and kwargs of {} failed to run.
Traceback (most recent call last):
  File "mysc\thread_utils.py", line 12, in new_func
  File "controller\mainController.py", line 283, in start
IndexError: list index out of range
```

**Comment by Mohamed00** [comment]
TWBlue's access was terminated as part of Twitter's new paid API plan. I'm not aware of any plans to restore Twitter support, and even if there was and TWBlue wasn't officially violating Twitter's terms of service now, the pricing would likely be unrealistic for a small project like this.

**Comment by SeanTolstoyevski** [comment]
maybe const API?

**Comment by manuelcortez** [comment]
Hi, despite we could pay the $100 a month that Twitter requires as part of their new API, we  are basically unable to bring back Twitter support due to a requirement added in their developer policy. Basically now it is not allowed to clone or offer a similar experience to what Twitter already offers in all platforms. That change bans officially all third party clients, as Twitter wants to be the only "client" of their own platform. So a new authorization method and stuff will not work when that's going to be reviewed.
