### ISSUE TITLE
Impossible to open user actions from followers or following buffer

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#575]
### Steps to reproduce.
1. Select a user from either the followers or following buffers.
2. Open the user actions dialog, either with the button in the GUI or the shortcut in the invisible interface.
### Expected.
The user actions dialog should open.
### Actual.
The user actions dialog doesn't open and the following traceback is displayed.
08/01/2024 17:22:18 root ERROR: Uncaught exception
Traceback (most recent call last):
  File "C:\TWBlue\src\controller\buffers\mastodon\base.py", line 291, in user_actions
    pub.sendMessage("execute-action", action="follow")
  File "C:\Python38\lib\site-packages\pubsub\core\publisher.py", line 216, in sendMessage
    topicObj.publish(**msgData)
  File "C:\Python38\lib\site-packages\pubsub\core\topicobj.py", line 452, in publish
    self.__sendMessage(msgData, topicObj, msgDataSubset)
  File "C:\Python38\lib\site-packages\pubsub\core\topicobj.py", line 482, in __sendMessage
    listener(data, self, allData)
  File "C:\Python38\lib\site-packages\pubsub\core\listener.py", line 237, in __call__
    cb(**kwargs)
  File "C:\TWBlue\src\controller\mainController.py", line 996, in execute_action
    getattr(self, action)(**kwargs)
  File "C:\TWBlue\src\controller\mainController.py", line 477, in follow
    return handler.follow(buffer=buffer)
  File "C:\TWBlue\src\controller\mastodon\handler.py", line 154, in follow
    if item.account.acct not in users:
  File "C:\Python38\lib\site-packages\mastodon\utility.py", line 64, in __getattr__
    raise AttributeError(f"Attribute not found: {attr}")
AttributeError: Attribute not found: account

**Comment by AbdullahMohammad96** [comment]
same problem here. started for me last night. i am not running it from source.
