### ISSUE TITLE
bug with the function to display a post (UnicodeEncodeError)

### ISSUE THREAD

**Issue by jeremyp3** [manuelcortez/TWBlue#637]
since twblue version 2024.05.19, if the user's display name contains accents or emojis, you can no longer see the message details, either with the keyboard shortcut or via the context menu.

python error:
19/05/2024 11:49:28 root ERROR: Uncaught exception
Traceback (most recent call last):
  File "keyboard_handler\wx_handler.py", line 72, in <lambda>
  File "keyboard_handler\wx_handler.py", line 99, in process_key
  File "keyboard_handler\main.py", line 47, in handle_key
  File "controller\mainController.py", line 533, in view_item
  File "controller\buffers\mastodon\base.py", line 553, in view_item
  File "controller\mastodon\messages.py", line 262, in __init__
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 969-970: character maps to <undefined>
19/05/2024 11:53:39 root ERROR: Uncaught exception
Traceback (most recent call last):
  File "keyboard_handler\wx_handler.py", line 72, in <lambda>
  File "keyboard_handler\wx_handler.py", line 99, in process_key
  File "keyboard_handler\main.py", line 47, in handle_key
  File "controller\mainController.py", line 533, in view_item
  File "controller\buffers\mastodon\base.py", line 553, in view_item
  File "controller\mastodon\messages.py", line 262, in __init__
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f60e' in position 1301: character maps to <undefined>

thanks !

**Comment by jeremyp3** [comment]
FYi, bug still present in release 2024-05-23

**Comment by jeremyp3** [comment]
is fixed, thanks !
